### ISSUE TITLE
Home-Copy kürzen

### ISSUE THREAD

**Issue by maxmaier** [codeOfThomasRutzer/munchable_app#5]
Die Copy auf der Home "Wie funktioniert das?" ist viel zu lang und trifft nicht immer auf das aktuelle Produkt zu. Die müsste man also noch kürzen.

@ThomasRutzer Ich glaube ich hab sogar schon mal eine Kürzung commited. Könnten wir die bei der nächsten Gelegenheit mal Live schalten?

**Comment by codeOfThomasRutzer** [comment]
sollte nun live einsehbar sein
